(function(){'use strict';
const OPS=[['new','جديد','#39a86b'],['swap','تبديل','#df9141'],['park','ركن','#d7b53e'],['reuse','إعادة استخدام','#4c94d8'],['service_end','إنهاء خدمة','#d95858']];let sel='';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const K=r=>window.EGOTireOps?.tireOperationKind?.(r?.operation)||'other';
const T=r=>Date.parse(String(r?.date||''))||0;
function R(){try{return typeof filters==='function'?(filters()||[]):(Array.isArray(DATA)?DATA:[])}catch(e){return []}}
function A(){try{return Array.isArray(DATA)?DATA:[]}catch(e){return []}}
function D(v){try{if(typeof datefmt==='function')return datefmt(v)}catch(e){}let d=new Date(v);return isNaN(d)?String(v||'—'):new Intl.DateTimeFormat('en-GB',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function current(scoped){let ids=new Set(scoped.map(r=>String(r.tire_id||'').trim()).filter(Boolean)),m=new Map();A().forEach(r=>{let id=String(r.tire_id||'').trim();if(!id||!ids.has(id))return;let old=m.get(id);if(!old || T(r)>T(old) || (T(r)===T(old) && (Number(r.id)||0)>(Number(old.id)||0))) m.set(id,r)});return [...m.values()]}
function status(r){let k=K(r);if(k==='park')return['parked','مركون — مستخدم سابقًا'];if(k==='service_end')return['ended','منتهي الخدمة / تالف'];if(['new','reuse','swap'].includes(k))return['installed','قيد الاستخدام'];return['unknown','تحتاج مراجعة']}
function render(){let scoped=R(),cur=current(scoped),stats=OPS.map(([kind,label,color])=>{let a=scoped.filter(r=>K(r)===kind),last=a.slice().sort((x,y)=>T(y)-T(x))[0];return{kind,label,color,count:a.length,unique:new Set(a.map(r=>String(r.tire_id||'').trim()).filter(Boolean)).size,last:last?.date||''}}),tot=stats.reduce((n,x)=>n+x.count,0),ss={installed:0,parked:0,ended:0,unknown:0};cur.forEach(r=>ss[status(r)[0]]++);
let x=document.getElementById('tireStatusCurrentKpis');if(x)x.innerHTML=[['إجمالي الهويات',cur.length,'هوية ضمن النطاق'],['قيد الاستخدام',ss.installed,'مركبة حاليًا'],['مركون بالمخزن',ss.parked,'مستخدم سابقًا ومتاح'],['منتهي الخدمة / تالف',ss.ended,'خروج نهائي']].map(a=>`<div class="tire-status-kpi"><span>${a[0]}</span><strong>${a[1].toLocaleString('en-US')}</strong><small>${a[2]}</small></div>`).join('');
x=document.getElementById('tireStatusOperationGrid');if(x)x.innerHTML=stats.map(a=>`<button class="tire-op-card ${sel===a.kind?'active':''}" data-kind="${a.kind}"><span>${a.label}</span><strong>${a.count.toLocaleString('en-US')}</strong><small>${a.unique} هوية فريدة</small></button>`).join('');
let mx=Math.max(1,...stats.map(a=>a.count));x=document.getElementById('tireStatusChart');if(x)x.innerHTML=stats.map(a=>`<div class="tire-status-bar-wrap" style="color:${a.color}"><div class="tire-status-bar-value">${a.count}</div><div class="tire-status-bar-track"><div class="tire-status-bar" style="height:${Math.max(3,a.count/mx*100)}%"></div></div><div class="tire-status-bar-label">${a.label}</div></div>`).join('');
x=document.getElementById('tireStatusSummaryBody');if(x)x.innerHTML=stats.map(a=>`<tr data-kind="${a.kind}"><td><b>${a.label}</b></td><td>${a.count}</td><td>${a.unique}</td><td>${tot?(a.count/tot*100).toFixed(1):'0.0'}%</td><td>${a.last?D(a.last):'—'}</td></tr>`).join('');
let ids=sel?new Set(scoped.filter(r=>K(r)===sel).map(r=>String(r.tire_id||'').trim())):null,det=ids?cur.filter(r=>ids.has(String(r.tire_id||'').trim())):cur,op=OPS.find(a=>a[0]===sel);document.getElementById('tireStatusDetailsTitle').textContent=op?'تفاصيل الكفرات — '+op[1]:'تفاصيل الكفرات';document.getElementById('tireStatusDetailsHint').textContent=det.length+' هوية';
x=document.getElementById('tireStatusDetailsBody');if(x)x.innerHTML=det.sort((a,b)=>T(b)-T(a)).map(r=>{let st=status(r);return`<tr><td><b>${E(r.tire_id||'—')}</b></td><td><span class="tire-status-badge ${st[0]}">${st[1]}</span></td><td>${E(r.operation||'—')}</td><td>${D(r.date)}</td><td>${E(r.tire_type||'—')}</td><td>${E(r.plate||r.vehicle||'—')}</td><td>${E(r.position||'—')}</td><td>${E(r.supplier||'—')}</td><td>${E(r.invoice||'—')}</td></tr>`}).join('')||'<tr><td colspan="9">لا توجد بيانات</td></tr>';
let hk=document.getElementById('homeMiniKpis_tireStatusReport');if(hk)hk.innerHTML=[['الهويات',cur.length],['مركون',ss.parked],['تالف',ss.ended]].map(a=>`<div class="home-mini-kpi"><span>${a[0]}</span><strong>${a[1]}</strong></div>`).join('');
document.querySelectorAll('#tireStatusReport [data-kind]').forEach(e=>e.onclick=()=>{sel=sel===e.dataset.kind?'':e.dataset.kind;render()})}
window.renderTireStatusReport=render;
document.addEventListener('click',e=>{if(e.target.closest('[data-report-target="tireStatusReport"]'))setTimeout(render,20)});
setInterval(()=>{if(document.getElementById('tireStatusReport')?.classList.contains('active'))render()},3000);setTimeout(render,300);
})();